theme = "adidoks"
base_url = "https://autoforecastteam.github.io"
title = "autoforecast team's blog"
description = ""
compile_sass = true
build_search_index = true
timeformat = "%e %B %Y"
timezone = "Europe/Warsaw"

taxonomies = [
  {name = "authors"},
  #{name = "tags"},
  #{name = "categories"}
]

docs_repo = "https://github.com/AutoForecastTeam/autoforecastteam.github.io"
repo_branch = "main"
edit_page = false

[markdown]
highlight_code = true
highlight_theme = "nyx-bold"

[extra]

[[extra.menu.main]]
name = "Posts"
section = "blog"
url = "/posts/"
weight = 20

[[extra.menu.main]]
name = "Authors"
section = "authors"
url = "/authors/"
weight = 30